version: '3.9'
services:
    backend:
        build: .
        ports:
            - 8000:8000
        volumes:
            - .:/app   # Map all the files to the app folder.
        depends_on:
            - db
    db:
        image: mysql:8
        restart: always
        environment:
            DB_HOST: db
            MYSQL_DATABASE: ambassador #Set up the container creds.
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql #Map a local DB Data to the Storage folder in Laravel.
        ports:
            - 33066:3306